### ISSUE TITLE
[DOCS] submodule 을 사용하여 aws codebuild 사용하기

### ISSUE THREAD

**Issue by WHO-A-U** [KIMJINOH97/Hotplace-map#121]
# git submodule 사용하기

## 개요
.env 파일과 같이 숨겨놓은 파일을 따로 submodule repo 로 만들어놓은후 한번에 불러오기사용

## 전략
1. 원래 repo 와 submodule repo 를 두어 한번에 clone 함
2. cp 명령어를 이용하여 원하는 위치에 적절하게 복사
3. gradle 명령어를 수행
4. gradle-wrapper.jar 를 s3 에 upload

## 방법 (예시)

1. root-repo 는 public , sub-repo 는 private 으로 만든다 (같은 계정으로 두개의 저장소를 만드는게 좋음) 

2. repository 관계 설정

`C:\Users\djfxl\Desktop\root-module> git submodule add https://github.com/WHO-A-U/sub-module.git` 
`git push origin main`

root-module 안에서 하위모듈에 대한 설정을 다음 커맨드를 이용하여 한다음
원격저장소에 update 

3. 관계가 설정이 되면 다음과 같이 

![image](https://user-images.githubusercontent.com/59171080/139593276-3bb43827-ad73-4913-8966-a01171eb5096.png)
설정이 완료된다

![image](https://user-images.githubusercontent.com/59171080/139592026-86df29c3-bcbc-4fc8-9d6e-06ad02044f46.png)

![image](https://user-images.githubusercontent.com/59171080/139592034-2e25d63b-9755-4e30-b18f-43aab8f69b56.png)

4. AWS code build 사용
![image](https://user-images.githubusercontent.com/59171080/139593300-5a65806a-77bf-475c-b597-dc113d015067.png)
root-module 을 target 으로 하고
git clone 깊이 full 과 git 하위 모듈(sub module ) 항목을 체크한다

5. AWS buildspec.yml 과 log 예시
**다음과 같이 buildspec.yml 을 작성했을떄 하위 모듈들이 잘 불러와진것을 볼수있다.**
```yml
phases:
  # install:
    #Ubuntu 표준 이미지 2.0 이상을 사용하는 경우 런타임 버전을 지정해야 합니다.
    #런타임 버전을 지정하는 경우 Ubuntu 표준 이미지 2.0 이외의 이미지를 사용하면 빌드에 실패합니다.
    #runtime-versions:
      # name: version
      # name: version
    #commands:
      # - command
      # - command
  pre_build:
    commands:
      - ls
      - pwd
      - cd sub-module
      - ls
      - ls -al
      - pwd
  build:
    commands:
      # - command
```

![image](https://user-images.githubusercontent.com/59171080/139593376-5ecf29a1-7c56-458c-8d50-b0a96e762aa4.png)

##  참고 링크

> https://stackoverflow.com/questions/42712542/how-to-auto-deploying-git-repositories-with-submodules-on-aws
> https://docs.aws.amazon.com/ko_kr/codebuild/latest/APIReference/API_GitSubmodulesConfig.html
